# Generated by Django 4.1.7 on 2024-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='news')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='places')),
            ],
            options={
                'db_table': 'Places',
            },
        ),
    ]
